# Generated by Django 4.0.4 on 2022-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_icon', models.CharField(max_length=100)),
                ('my_des', models.TextField()),
            ],
        ),
    ]
