# Generated by Django 4.0.4 on 2022-05-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slug',
            new_name='new_slug',
        ),
    ]
