# Generated by Django 4.0.4 on 2022-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_slug_news_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default=None, max_length=400, null=True, upload_to='news/'),
        ),
    ]
